### ISSUE TITLE
Issue-Add sparkline widget and fix warnings

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/solana-2#13]
Automated Review Comments
Issues in examples/prototype.rs:
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
Issues in src/widgets/sparkline.rs:
  - (54, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')

**Comment by drone-1x** [comment]
I got it.
