### ISSUE TITLE
Issue-Change layout properties and improve gauge and sparkline

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/solana-2#17]
Automated Review Comments
Issues in examples/prototype.rs:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
Issues in src/buffer.rs:
  - (6, 'Hardcoded string found')
Issues in src/widgets/block.rs:
  - (42, 'Line exceeds 80 characters')
Issues in src/widgets/sparkline.rs:
  - (17, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
