### ISSUE TITLE
Issue-Update color support for block, gauge, list and sparkline

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/solana-2#23]
Automated Review Comments
Issues in src/buffer.rs:
  - (6, 'Line exceeds 80 characters')
Issues in src/widgets/gauge.rs:
  - (12, 'Line exceeds 80 characters')
Issues in src/widgets/list.rs:
  - (20, 'Line exceeds 80 characters')
Issues in src/widgets/sparkline.rs:
  - (46, 'Line exceeds 80 characters')

**Comment by drone-1x** [comment]
I got it.
