### ISSUE TITLE
Issue-Improve Chart Widget, safer buffer and unicode width

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/solana-2#31]
Automated Review Comments
Issues in examples/prototype.rs:
  - (6, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
Issues in src/buffer.rs:
  - (63, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
Issues in src/widgets/chart.rs:
  - (54, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
