### ISSUE TITLE
Issue-Update prototype

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/solana-2#50]
Automated Review Comments
Issues in examples/prototype.rs:
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')

**Comment by drone-1x** [comment]
I got it.
