### ISSUE TITLE
Issue-Change rendering method and adapt widget trait accordingly

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/solana-2#54]
Automated Review Comments
Issues in examples/block.rs:
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in examples/prototype.rs:
  - (3, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
Issues in src/buffer.rs:
  - (19, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
Issues in src/layout.rs:
  - (32, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
Issues in src/terminal.rs:
  - (83, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
Issues in src/widgets/barchart.rs:
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
Issues in src/widgets/block.rs:
  - (34, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
Issues in src/widgets/chart.rs:
  - (32, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
Issues in src/widgets/gauge.rs:
  - (60, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
Issues in src/widgets/list.rs:
  - (37, 'Line exceeds 80 characters')
Issues in src/widgets/text.rs:
  - (35, 'Line exceeds 80 characters')

**Comment by drone-1x** [comment]
I got it.
