### ISSUE TITLE
Issue-Fix redraw for disappearing widgets

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/solana-2#8]
Automated Review Comments
Issues in examples/prototype.rs:
  - (21, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
Issues in src/terminal.rs:
  - (5, 'Hardcoded string found')

**Comment by doraemon-35** [comment]
I got it.
